apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  containers:
  - name: mysql
    image: mysql
    volumeMounts:
      - mountPath: /data/db
        name: mysql-pvc
    ports:
    - containerPort: 3306
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: paswrd
    envFrom:
      - secretRef:
          name: app-secret
  volumes:
    - name: mysql-pvc
      persistentVolumeClaim:
        claimName: mysql-pvc