kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-bind
  namespace: final
subjects:
- kind: ServiceAccount
  name: clo835
  namespace: final
  apiGroup: ""
roleRef:
  kind: Role
  name: Roles
  apiGroup: rbac.authorization.k8s.io