apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webapp-mysql
  labels:
    app: example-app
    name: simple-webapp-mysql
spec:
  selector:
    matchLabels:
      name: simple-webapp-mysql
  replicas: 1
  template:
    metadata:
      labels:
        name: simple-webapp-mysql
    spec:
      serviceAccountName: clo835
      containers:
      - name: simple-webapp-mysql
        image: 969581184687.dkr.ecr.us-east-1.amazonaws.com/simple_webapp_mysql:latest
        ports:
        - containerPort: 81
        envFrom:
          - secretRef:
              name: app-secret
          - configMapRef:
              name: swbapp-config
